// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BingeBot.Data;

#nullable disable

namespace BingeBot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241108153933_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BingeBot.Services.JobRecord", b =>
                {
                    b.Property<Guid>("TrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Command")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ExecuteAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpireOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Result")
                        .HasColumnType("BLOB");

                    b.HasKey("TrackingID");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
